### ISSUE TITLE
请问您是如何修改并重新编译chromium的

### ISSUE THREAD

**Issue by tiga210** [thouger/anti_taobao_login_chrome#1]
请问您是如何修改并重新编译chromium的

**Comment by thouger** [comment]
我是按照这里来的,https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#Faster-builds
这个对现在还适用

**Comment by thouger** [comment]
我是按照官方教程来的,这个教程对现在还适用
https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md

**Comment by tiga210** [comment]
我发现有一个问题，headless不行

**Comment by thouger** [comment]
不行是什么意思,是指navigator.webdriver true了?

**Comment by tiga210** [comment]
当headless的时候就登录不了淘宝，难道是淘宝还有可视化检测？你可以试试看

**Comment by thouger** [comment]
淘宝已经更新了反爬策略了,之前的方法已经不能用了,滑条已经划不过去了,现在没有精力看

**Comment by tiga210** [comment]
好的，目前我测试  非headless情况下 滑块还是可以滑的

**Comment by thouger** [comment]
更新一下,还是可以挂过去的...今天发现我的这个项目被保存到北极了...
